### ISSUE TITLE
[Question] Best practice for creating and defining a Button component

### ISSUE THREAD

**Issue by talves** [damassi/gatsby-starter-typescript-rebass-netlifycms#1]
Before I start: This is awesome work. I ❤ the use of netlify-cms-backend-fs 😀

Is there a straight forward way to create a component and have it defined?

![image](https://user-images.githubusercontent.com/784848/51790111-f47fff80-2145-11e9-82d3-5e9d25f47b05.png)

**Comment by damassi** [comment]
Hi @talves - Yup, you need to pass it [into the scope here](https://github.com/damassi/gatsby-starter-typescript-rebass-netlifycms/blob/master/src/cms/cms.jsx#L47-L53). I added a few comments to make that a bit clearer! 

<img width="1056" alt="screen shot 2019-01-26 at 9 55 39 am" src="https://user-images.githubusercontent.com/236943/51790945-9b699900-2150-11e9-9e36-d524ea834c82.png">

**Comment by damassi** [comment]
The file-system plugin is working fantastic. (I wish it was baked into the NetlifyCMS core.)

**Comment by talves** [comment]
Yeah, Shawn and I have gone round and round on this. We were not sure how it would be received by the community.  I started it a LONG time ago and got a lot of push back at that time, because we did not have all the features in that we have now.

I wanted it to be a small entry point for most projects and I think we are there now.

**Comment by talves** [comment]
This MDX example really has made me realize we might be overthinking the issues with MDX.

**Comment by damassi** [comment]
That was exactly my thought as well 😉 I'm building an interactive design system at work and we've got tons of docs with examples and everything "just works" inside of NetlifyCMS following this pattern. All that was required is the proper scope, which can be shared. It was really quite straightforward to setup!

**Comment by talves** [comment]
I have been avoiding MDX for awhile, but NOT now. Thanks for sharing this example.

**Comment by talves** [comment]
sorry, how do you handle the build in this use case
![image](https://user-images.githubusercontent.com/784848/51791526-58f88a00-2159-11e9-9c88-b79ae8f80bf2.png)

importing of the `Button` is missing in the MDX

**Comment by damassi** [comment]
@talves - fixed in https://github.com/damassi/gatsby-starter-typescript-rebass-netlifycms/pull/2
