### ISSUE TITLE
Error editing MDX docs

### ISSUE THREAD

**Issue by whoisryosuke** [damassi/gatsby-starter-typescript-rebass-netlifycms#4]
1. Clone repo
1. `npm i`
1. `npm run develop`
1. Browse to http://localhost:8000/admin/#/collections/mdx/entries/hello
1. Following error received: 

```
Error
There's been an error - please report it.

Details
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Markdown docs work fine. All the MDX docs display the error.

## Gatsby info:

```

  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.76 => 2.13.72 
    gatsby-image: ^2.0.20 => 2.2.10 
    gatsby-mdx: ^0.3.4 => 0.3.6 
    gatsby-plugin-catch-links: ^2.0.9 => 2.1.4 
    gatsby-plugin-manifest: ^2.0.9 => 2.2.6 
    gatsby-plugin-netlify-cms: ^3.0.10 => 3.0.18 
    gatsby-plugin-offline: ^2.0.16 => 2.2.7 
    gatsby-plugin-sharp: ^2.0.14 => 2.2.13 
    gatsby-plugin-styled-components: ^3.0.4 => 3.1.2 
    gatsby-plugin-typescript: ^2.0.3 => 2.1.3 
    gatsby-source-filesystem: ^2.0.16 => 2.1.10 
    gatsby-transformer-sharp: ^2.1.8 => 2.2.7 
  npmGlobalPackages:
    gatsby-cli: 2.7.8
```

**Comment by jcharlesworthuk** [comment]
I ran into a similar issue to this, I think it is caused by using npm as the task runner.  Didn't find a solution but I did find that using yarn worked fine `yarn start`

**Comment by damassi** [comment]
Very odd! I haven't used `npm` in a long time so I've never come across this issue.

**Comment by whoisryosuke** [comment]
Tried using yarn, got the server running, and opened a whole new can of worms 🤣

Got this error for the site index:

```
Failed to compile
GraphQL Error Unknown type "ImageSharpFixed".

  file: /Users/photoroom/Development/React/ksc-netlify-cms/node_modules/gatsby-transformer-sharp/src/fragments.js

  1 | 
> 2 |   fragment GatsbyImageSharpFixed on ImageSharpFixed {
    |                                     ^
  3 |     base64
  4 |     width
  5 |     height
  6 |     src
  7 |     srcSet
  8 |   }
  9 | 
This error occurred during the build time and cannot be dismissed
```

Got this one trying to edit a post in Netlify Admin:

```
Error
There's been an error - please report it.

Details
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

Not sure what I'm doing wrong on my end, could totally see it being NPM. Gonna try to delete node modules and reinstall using yarn (got an error on `yarn start` that I was missing a TS package, might as well reinstall).

***

After deleting the `node_modules` folder and using `yarn install`, I was able to get things running ✅ Had a small Typescript error that it couldn't read an eslint plugin config, but the site and admin load now 👍

Thanks for the suggestion @jcharlesworthuk 🙌👏

***

Not sure how this template could resolve this, since the errors seemed linked to the way the package managers handle some dependencies (probably Typescript). I'm going to add a PR to add a clear note in the README that `yarn` is a requirement for devs that don't default to it.

I'll close this unless someone else encounters a similar issue 😊👍
